virtual_button:
  name: "Virtual button"
  description: "Generate a virtual button event on MLGW"
  fields:
    button:
      name: "Button"
      description: "The button number, in the range 1 to 255"
      example: 1
      required: true
      selector:
        number:
          min: 1
          max: 255
          mode: box
    action:
      name: "Action"
      description: "This parameter (available since MLGW SW 2.2) determines the button action"
      example: "PRESS"
      required: true
      default: "PRESS"
      selector:
        select:
          options:
            - "PRESS"
            - "HOLD"
            - "RELEASE"

all_standby:
  name: "All Standby"
  description: "Send global command All_Standby"
